jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://93.68.156.15:8082/notifyGithubEvent'
        method: 'POST'
        data: '{"teamToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNZXNzaSIsImJhdHRsZV9jb2QiOiJCXzJBMTI5IiwidGVhbV9uYW1lIjoibWVzc2lUZWFtIiwiaWF0IjoxNzA2ODMwODY4LCJleHAiOjE3MzgzNjY4Njh9.-__Wdts9pddfkLMXJ9s1pLie-y8ohCCpLTHjdFwX_m0", "githubRepository": "githubRepository=https://github.com/Andre04-poli/ciccio"}'