name: Notify Codekatabattle System

on:
  push:
    branches:
      - master

jobs:
  invoke-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v2

    - name: Invoke API
      run: |
        curl -X POST -d "linkGitub=https://github.com/Andre04-poli/ciccio&token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNZXNzaSIsImJhdHRsZV9jb2QiOiJCXzJBMTI5IiwidGVhbV9uYW1lIjoibWVzc2lUZWFtIiwiaWF0IjoxNzA2ODMwODY4LCJleHAiOjE3MzgzNjY4Njh9.-__Wdts9pddfkLMXJ9s1pLie-y8ohCCpLTHjdFwX_m0" https://93.68.156.15:8082/notifyGithubEvent
